### ISSUE TITLE
Merge with remotedebug-ios-webkit-adapter?

### ISSUE THREAD

**Issue by auchenberg** [artygus/devtools-compat-proxy#2]
Hey man,

Dont have you on twitter or email. At Microsoft we have build https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter, which is a more well build adapter.

Wanna join forces?

/k

**Comment by artygus** [comment]
Hey @auchenberg, thanks for the invitation! Looks like really good stuff, but I don't think I have enough free time for proper contributions, though I'll follow the project and post a link in ios-webkit-debug-proxy readme

**Comment by artygus** [comment]
PS. you can ping me on twitter, it's @artygus

**Comment by auchenberg** [comment]
Cool, just wanted to give you a heads up, as the project is using your great work, and aims to implement the API differences.
